#!/usr/bin/env python
from sys import argv
import re
import argparse
import tailer

# Default, because
colors = {
    'RED':  ['ERROR', 'kernel', '500'],
    'ORANGE': ['WARNING'],
    'YELLOW': ['404', '403'],
    'GREEN':  ['200', 'OK'],
    'BABYBLUE':  ['INFO']
}

# Argument Parser
parser = argparse.ArgumentParser(
                prog="ninetails", 
                description="ninetails is a log monitoring tool that helps you read and understand logs")

# Set Arguments
parser.add_argument('file', nargs='?', help='file to watch')
parser.add_argument('-t', '--tail', nargs='?', const=10, type=int, help="tail log")
parser.add_argument('-e', help='Highlight only matched text rather than line', action="store_false")
args = parser.parse_args()

#print args

if args.file is None:
    parser.print_help()
    exit()

class text:

    PURPLE="\033[38;5;129m"
    PINK="\033[38;5;162m"
    RED="\033[38;5;196m"
    ORANGE = '\033[38;5;208m'
    YELLOW='\033[38;5;184m'
    GREEN="\033[38;5;154m"
    BLUE='\033[38;5;32m'
    GREY="\033[38;5;242m"
    DARKGREY="\033[38;5;239m"
    LIGHTGREY="\033[38;5;249m"
    BABYBLUE='\033[38;5;123m'
    LIGHTPINK='\033[38;5;212m'
    WHITE="\033[38;5;7m"
    CLEAR="\033(B\033[m" #$(tput sgr0)

try:
    if args.tail is not None:
        print text.WHITE,"---- Nine Tails attacked with Tail Whip ----", text.CLEAR
        for line in tailer.tail(open(args.file), args.tail):
            message = "%s%s" % (text.DARKGREY, line)
            for color in colors: 
                for match in colors[color]:
                    if re.match(".*(%s).*" % match, line):
                        message = "%s%s" % (getattr(text, color), line)

            print message
        print text.WHITE,"---- Tail Whip Finished ----", text.CLEAR

    for line in tailer.follow(open(args.file)):
        message = "%s%s" % (text.DARKGREY, line)
        for color in colors: 
            for match in colors[color]:
                if re.match(".*(%s).*" % match, line):
                    message = "%s%s" % (getattr(text, color), line)

        print message

except KeyboardInterrupt, e:
    pass
