#!/usr/bin/env python
from sys import argv
import re
import argparse

import tailer

show_last_lines = False

colors = {
    'RED':  ['sudo', 'kernel', '500'],
    'ORANGE': ['login'],
    'YELLOW': ['404'],
    'GREEN':  ['py', 'php', 'launch', '200'],
    'BABYBLUE':  ['discoveryd']
}

parser = argparse.ArgumentParser(description='Ninetails is a log monitoring solution')

class text:

    PURPLE="\033[38;5;129m"
    PINK="\033[38;5;162m"
    RED="\033[38;5;196m"
    ORANGE = '\033[38;5;208m'
    YELLOW='\033[38;5;184m'
    GREEN="\033[38;5;154m"
    BLUE='\033[38;5;32m'
    GREY="\033[38;5;242m"
    DARKGREY="\033[38;5;239m"
    LIGHTGREY="\033[38;5;249m"
    BABYBLUE='\033[38;5;123m'
    LIGHTPINK='\033[38;5;212m'
    WHITE="\033[38;5;7m"
    CLEAR="\033(B\033[m" #$(tput sgr0)

try:
    if show_last_lines:
        print text.WHITE,"---- Nine Tails attacked with Tail Whip ----", text.CLEAR
        for line in tailer.tail(open(argv[1]), 10):
            message = "%s%s" % (text.DARKGREY, line)
            for color in colors: 
                for match in colors[color]:
                    if re.match(".*(%s).*" % match, line):
                        message = "%s%s" % (getattr(text, color), line)

            print message
        print text.WHITE,"---- Tail Whip Finished ----", text.CLEAR

    for line in tailer.follow(open(argv[1])):
        message = "%s%s" % (text.DARKGREY, line)
        for color in colors: 
            for match in colors[color]:
                if re.match(".*(%s).*" % match, line):
                    message = "%s%s" % (getattr(text, color), line)

        print message

except KeyboardInterrupt, e:
    pass
